### ISSUE TITLE
Maximum depth for a particular item in a list

### ISSUE THREAD

**Issue by Oznkskn** [Elektrochecker/shpd-seed-finder#1]
Could you add a way to select the floor a particular item will be in when searching for a seed.

E.g. for a seed where, the imp gives you +4 haste ring and you get a sharpshooting ring in the servers.

**Comment by Elektrochecker** [comment]
Conditional finding is something I could add some time in the future, but it is hard to find the time right now.

In the mean time its hopefully good enough to inspect the few found seeds for your items in a text editor
